version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
  worker:
    build:
      context: https://github.com/den19980107/tix-worker.git#main
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=$DATABASE_URL
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
      - NEXTAUTH_URL=$NEXTAUTH_URL
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - TIX_WORKER_URL=$TIX_WORKER_URL
