version: '3'

# test
services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    env_file:
      - stack.env
    pull_policy: build
  worker:
    build:
      context: https://github.com/den19980107/tix-worker.git#main
      dockerfile: Dockerfile
    ports:
      - "3004:8080"
    env_file:
      - stack.env
    pull_policy: build
